### ISSUE TITLE
Backspace action names are inconsistent

### ISSUE THREAD

**Issue by todofixthis** [vsch/MissingInActions#1]
The MissingInActions plugin provides a keymap action called 'Backspace to Word End in Different "CamelHumps" Mode not EOL'.

I believe this is supposed to be named 'Backspace to Word _Start_ in Different "CamelHumps" Mode not EOL'

This would make it consistent with naming of the "Delete to Word End" actions.

<img width="439" alt="'Delete to Word End' Actions" src="https://cloud.githubusercontent.com/assets/202040/20545349/bc8d5ae0-b0dc-11e6-969f-e12f429038bf.png">

<img width="478" alt="'Backspace to Word Start/End' Actions" src="https://cloud.githubusercontent.com/assets/202040/20545350/bcafd5d4-b0dc-11e6-9765-ead2cfef5d98.png">

**Comment by vsch** [comment]
@todofixthis, you are right and I wanted to name it that way but the IDE has all the delete to previous word actions named as delete.

I will change it for the next release.

Please let me know if there are any actions on your wish list. I am expanding the functionality to make text editing a lot more fun. I already cannot live without the line selections, multi-caret safe ops.

**Comment by todofixthis** [comment]
Sorry; I didn't explain it very well.  I think the naming convention you adopted is correct; the inconsistency is here:

```
Delete to Word End in Different "CamelHumps" Mode not EOL
Delete to Word End not EOL
Backspace to Word End in Different "CamelHumps" Mode not EOL  <-- Word End or Word Start?
Backspace to Word Start not EOL
```

I am super excited that you have created this plugin; I've been waiting for this functionality for years (:  Really appreciate all the hard work, and I hope that my feedback is helpful!

**Comment by vsch** [comment]
@todofixthis, I will review these for consistency of names and operation. They were just modified copies from the community edition source, not my reworked versions. They desperately need attention.

Glad to know there is more than just me who is fed up with text editing limitations in the IDEs.

You should try the line mode and the selection <--> multi caret functions. I can hardly use the IDE multi-caret mode because I always have to manually create them where as there is always a selection first.

Also added the "Select pasted text" for that reason. 

Here is my typical work flow:

1. Select some code lines (99% it is full lines, so I use line mode which lets me do it without loosing caret column position or having to keep going back to the left edge)
2. copy 
2. paste it where needed
3. Already selected (select pasted text option in plugin config)
4. Optionally trim selection (both ends using switch selection direction action)
5. Switch selection to multi-carets (toggle selection/multi-carets action)
6. Optionally remove carets on blank lines (remove blank line carets)
7. Do multi-caret chop and slice (using the multi-caret safe actions, carets stay on their lines)
8. Can switch back to selection if needed

I will be adding a selection stack and recall so at least the last few selections could be recalled. I am fed up of having to re-select the same stuff over and over again. So much wasted time. In my editor selections were always stored on a stack and you could recall previous ones.

Multi-caret mode is going to be getting a serious upgrade in the next release. I just have to first release  my other plugin: [Markdown Navigator](https://plugins.jetbrains.com/plugin/7896?pr=idea) it needs compatibility with 2016.3 versions.
